//
// Created by SERT on 13.01.2024.
//

#ifndef ROBOTER_STEUERUNG_JETSON_NANO_CONFIG_HPP
#define ROBOTER_STEUERUNG_JETSON_NANO_CONFIG_HPP

#define CHECKPOINT_PATH "model/detect.tflite"
#define LABELMAP_PATH "model/labelmap.txt"

#endif //ROBOTER_STEUERUNG_JETSON_NANO_CONFIG_HPP
